name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Check if package-lock.json exists
      - name: Check for package-lock.json
        id: check-lockfile
        run: |
          if [ -f "package-lock.json" ]; then
            echo "lockfile=true" >> $GITHUB_OUTPUT
          else
            echo "lockfile=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: ${{ steps.check-lockfile.outputs.lockfile == 'true' && 'npm' || '' }}

      - name: Install dependencies
        # Use npm ci if lock file exists, otherwise use npm install
        run: |
          if [ "${{ steps.check-lockfile.outputs.lockfile }}" == "true" ]; then
            npm ci
          else
            npm install
          fi
        shell: bash

      - name: Lint
        run: npx eslint src/**/*.ts --max-warnings=0

      - name: Test
        run: npm test
        # No OpenAI API key needed as tests use mocks

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 